# iTEBD

The infinite time-evolving block decimation (iTEBD) algorithm

In [1]:
import Tor10
import numpy as np
import copy

## Transfer Field Ising Model (TFIM)

$$
  H 
  = \sum_i J S^z_i S^z_{i+1} - h S^x_i
  = \sum_i J S^z_i S^z_{i+1} - \frac{h}{2} \left( S^x_i I_{i+1} + I_i S^x_{i+1}\right)
  = \sum_i h_{i,i+1}.
$$
$$
  h_{i,i+1} = J S^z_i S^z_{i+1} - \frac{h}{2} \left( S^x_i I_{i+1} + I_i S^x_{i+1}\right).
$$

### One-site operators

In [2]:
# one-site operators
Id = Tor10.UniTensor(bonds=[Tor10.Bond(2), Tor10.Bond(2)], N_rowrank=1, name = 'Id')
Id.SetElem([1, 0,\
            0, 1])
Sx = Tor10.UniTensor(bonds=[Tor10.Bond(2), Tor10.Bond(2)], N_rowrank=1, name = 'Sx')
Sx.SetElem([0, 1,\
            1, 0])
Sz = Tor10.UniTensor(bonds=[Tor10.Bond(2), Tor10.Bond(2)], N_rowrank=1, name = 'Sz')
Sz.SetElem([1, 0,\
            0,-1])

print(Id)
Id.Print_diagram()
print(Sx)
Sx.Print_diagram()
print(Sz)
Sz.Print_diagram()
# Sz.SetLabels([-10, -20])
# Sz.Print_diagram()

Tensor name: Id
is_diag    : False
tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

-----------------------
tensor Name : Id
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 1  
           \             /     
            -------------      
Tensor name: Sx
is_diag    : False
tensor([[0., 1.],
        [1., 0.]], dtype=torch.float64)

-----------------------
tensor Name : Sx
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 1  
           \             /     
            -------------      
Tensor name: Sz
is_diag    : False
tensor([[ 1.,  0.],
        [ 0., -1.]], dtype=torch.float64)

-----------------------
tensor Name : Sz
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      

### Two-site operators

In [22]:
# Sz1⨂Sz2
Sz1 = copy.deepcopy(Sz)
Sz2 = copy.deepcopy(Sz)
Sz1.SetLabels([0, 2])
Sz2.SetLabels([1, 3])
Sz1.Print_diagram()
Sz2.Print_diagram()
Sz1_Sz2 = Tor10.Contract(Sz1, Sz2)
Sz1_Sz2.SetName('Sz1⨂Sz2')
print(Sz1_Sz2)
Sz1_Sz2.Print_diagram()
ZZ = Sz1_Sz2.Reshape([4, 4], N_rowrank=1)
ZZ.Print_diagram()
print(ZZ)

-----------------------
tensor Name : Sz
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 2  
           \             /     
            -------------      
-----------------------
tensor Name : Sz
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     1 ____| 2         2 |____ 3  
           \             /     
            -------------      
Tensor name: Sz1⨂Sz2
is_diag    : False
tensor([[[[ 1.,  0.],
          [ 0.,  0.]],

         [[ 0., -1.],
          [ 0., -0.]]],


        [[[ 0.,  0.],
          [-1., -0.]],

         [[ 0., -0.],
          [-0.,  1.]]]], dtype=torch.float64)

-----------------------
tensor Name : Sz1⨂Sz2
tensor Rank : 4
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     

In [23]:
# Sx1⨂Id2
Sx1 = copy.deepcopy(Sx)
Id2 = copy.deepcopy(Id)
Sx1.SetLabels([0, 2])
Id2.SetLabels([1, 3])
Sx1_Id2 = Tor10.Contract(Sx1, Id2)
Sx1_Id2.SetName('Sx1⨂Id2')
Sx1_Id2.Print_diagram()
print(Sx1_Id2.Reshape([4, 4], N_rowrank=1))

# Id1⨂Sx2
Id1 = copy.deepcopy(Id)
Sx2 = copy.deepcopy(Sx)
Id1.SetLabels([0, 2])
Sx2.SetLabels([1, 3])
Id1_Sx2 = Tor10.Contract(Id1, Sx2)
Id1_Sx2.SetName('Id1⨂Sx2')
Id1_Sx2.Print_diagram()
print(Id1_Sx2.Reshape([4, 4], N_rowrank=1))

# Sz1⨂Id2
Sz1 = copy.deepcopy(Sz)
Id2 = copy.deepcopy(Id)
Sz1.SetLabels([0, 2])
Id2.SetLabels([1, 3])
Sz1_Id2 = Tor10.Contract(Sz1, Id2)
Sz1_Id2.SetName('Sz1⨂Id2')
Sz1_Id2.Print_diagram()
print(Sz1_Id2.Reshape([4, 4], N_rowrank=1))

# Id1⨂Sz2
Id1 = copy.deepcopy(Id)
Sz2 = copy.deepcopy(Sz)
Id1.SetLabels([0, 2])
Sz2.SetLabels([1, 3])
Id1_Sz2 = Tor10.Contract(Id1, Sz2)
Id1_Sz2.SetName('Id1⨂Sx2')
Id1_Sz2.Print_diagram()
print(Id1_Sz2.Reshape([4, 4], N_rowrank=1))

-----------------------
tensor Name : Sx1⨂Id2
tensor Rank : 4
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 2  
           |             |     
     1 ____| 2         2 |____ 3  
           \             /     
            -------------      
Tensor name: 
is_diag    : False
tensor([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]], dtype=torch.float64)

-----------------------
tensor Name : Id1⨂Sx2
tensor Rank : 4
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 2  
           |             |     
     1 ____| 2         2 |____ 3  
           \             /     
            -------------      
Tensor name: 
is_diag    : False
tensor([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 

### Linear algebra only accept rank-2 tensor with N_rowrank=1=N_columnrank

In [24]:
J = 1.0
hx = 1.0

Ham_12 = Sz1_Sz2*J + (Sx1_Id2+Id1_Sx2)*hx/2
Ham_12.SetName('Ham_12')
print(Ham_12)
Ham_12.Print_diagram()
Tor10.ExpH(Ham_12)

Tensor name: Ham_12
is_diag    : False
tensor([[[[ 1.0000,  0.5000],
          [ 0.5000,  0.0000]],

         [[ 0.5000, -1.0000],
          [ 0.0000,  0.5000]]],


        [[[ 0.5000,  0.0000],
          [-1.0000,  0.5000]],

         [[ 0.0000,  0.5000],
          [ 0.5000,  1.0000]]]], dtype=torch.float64)

-----------------------
tensor Name : Ham_12
tensor Rank : 4
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 2  
           |             |     
     1 ____| 2         2 |____ 3  
           \             /     
            -------------      


Exception: ('ExpH(a)', 'a should be rank-2 tensor with 1 inbond 1 outbond')

In [25]:
H_12 = Ham_12.Reshape([4, 4],  N_rowrank=1)
H_12.SetName('H_12')
print(H_12)
H_12.Print_diagram()
Tor10.ExpH(H_12)

Tensor name: H_12
is_diag    : False
tensor([[ 1.0000,  0.5000,  0.5000,  0.0000],
        [ 0.5000, -1.0000,  0.0000,  0.5000],
        [ 0.5000,  0.0000, -1.0000,  0.5000],
        [ 0.0000,  0.5000,  0.5000,  1.0000]], dtype=torch.float64)

-----------------------
tensor Name : H_12
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 4         4 |____ 1  
           \             /     
            -------------      
Tensor name: 
is_diag    : False
tensor([[3.1324, 0.6841, 0.6841, 0.4141],
        [0.6841, 0.5889, 0.2210, 0.6841],
        [0.6841, 0.2210, 0.5889, 0.6841],
        [0.4141, 0.6841, 0.6841, 3.1324]], dtype=torch.float64)


### Otimes always create a rank-2 tensor with N_rowrank=1=N_columnrank
Alternatively, one can use otimes.

In [7]:
# two-site operators
SzSz = Tor10.Otimes(Sz, Sz)
SzSz.SetName('SzSz')
SxId = Tor10.Otimes(Sx, Id)
IdSx = Tor10.Otimes(Id, Sx)
print(SzSz)
SzSz.Print_diagram()

Tensor name: SzSz
is_diag    : False
tensor([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0., -0.],
        [ 0.,  0., -1., -0.],
        [ 0., -0., -0.,  1.]], dtype=torch.float64)

-----------------------
tensor Name : SzSz
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 4         4 |____ 1  
           \             /     
            -------------      


In [14]:
J = -1.0
hx = 0.0

Ham = SzSz*J + (SxId+IdSx)*hx/2
Ham.SetName('Ham')
print(Ham)
print(Ham.Print_diagram())
Tor10.ExpH(Ham)

Tensor name: Ham
is_diag    : False
tensor([[-1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0., -1.]], dtype=torch.float64)

-----------------------
tensor Name : Ham
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 4         4 |____ 1  
           \             /     
            -------------      
None
Tensor name: 
is_diag    : False
tensor([[0.3679, 0.0000, 0.0000, 0.0000],
        [0.0000, 2.7183, 0.0000, 0.0000],
        [0.0000, 0.0000, 2.7183, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.3679]], dtype=torch.float64)


## Exp(Ham)

In [15]:
dtau = 0.1
print(Tor10.ExpH(H_12*(-dtau)))
print(Tor10.ExpH(Ham*(-dtau)))

expH = Tor10.ExpH(H_12*(-dtau))
print(expH)
print(expH.Print_diagram())
expH_12 = expH.Reshape([2, 2, 2, 2], N_rowrank=2)
print(expH_12)
print(expH_12.Print_diagram())

Tensor name: 
is_diag    : False
tensor([[ 1.1058e+00, -2.5052e-02, -2.5052e-02,  6.4703e-04],
        [-2.5052e-02,  9.0544e-01,  6.0532e-04, -2.5052e-02],
        [-2.5052e-02,  6.0532e-04,  9.0544e-01, -2.5052e-02],
        [ 6.4703e-04, -2.5052e-02, -2.5052e-02,  1.1058e+00]],
       dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[1.1052, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.9048, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.9048, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.1052]], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[ 1.1058e+00, -2.5052e-02, -2.5052e-02,  6.4703e-04],
        [-2.5052e-02,  9.0544e-01,  6.0532e-04, -2.5052e-02],
        [-2.5052e-02,  6.0532e-04,  9.0544e-01, -2.5052e-02],
        [ 6.4703e-04, -2.5052e-02, -2.5052e-02,  1.1058e+00]],
       dtype=torch.float64)

-----------------------
tensor Name : 
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
     

## iTEBD
Time to iTEBD.

## Set up parameters, Hamiltonian, exp(Hamiltonian)

In [33]:
# set up parameters
J = -1.0
hx = 4.0
D = 10
dtau = 0.1

In [34]:
# set up two-site Hamiltonian
Ham_12 = Sz1_Sz2*J + (Sx1_Id2+Id1_Sx2)*hx/2
Ham_12.SetName('Ham_12')
# print(Ham_12)
# Ham_12.Print_diagram()
H_12 = Ham_12.Reshape([4, 4],  N_rowrank=1)
H_12.SetName('H_12')
# print(H_12)
# H_12.Print_diagram()

# set up exp(H_12*(-dtau))
expH = Tor10.ExpH(H_12*(-dtau))
# print(expH)
# print(expH.Print_diagram())
expH_12 = expH.Reshape([2, 2, 2, 2], N_rowrank=2)
expH_12.SetName('exp(H_12*(-dtau))')
# print(expH_12)
print(Ham_12.Print_diagram())
print(expH_12.Print_diagram())

-----------------------
tensor Name : Ham_12
tensor Rank : 4
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 2  
           |             |     
     1 ____| 2         2 |____ 3  
           \             /     
            -------------      
None
-----------------------
tensor Name : exp(H_12*(-dtau))
tensor Rank : 4
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ 2  
           |             |     
     1 ____| 2         2 |____ 3  
           \             /     
            -------------      
None


## Initilize MPS

In [35]:
## Create MPS:
#
#     |    |     
#   --A-la-B-lb-- 
#
A = Tor10.UniTensor(bonds=[Tor10.Bond(D), Tor10.Bond(2), Tor10.Bond(D)], N_rowrank=1, labels=[-1,0,-2])
A.Rand()
A.SetName('A')
A.Print_diagram()

B = Tor10.UniTensor(bonds=A.bonds,N_rowrank=1,labels=[-3,1,-4])
B.Rand()
B.SetName('B')
B.Print_diagram()

la = Tor10.UniTensor(bonds=[Tor10.Bond(D),Tor10.Bond(D)], N_rowrank=1, labels=[-2,-3],is_diag=True)
la.Rand()
la.SetName('la')
print(la)
la.Print_diagram()

lb = Tor10.UniTensor(bonds=la.bonds, N_rowrank=1, labels=[-4,-5],is_diag=True)
lb.Rand()
lb.SetName('lb')
print(lb)
lb.Print_diagram()

-----------------------
tensor Name : A
tensor Rank : 3
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -1 ____| 10        2 |____ 0  
           |             |     
           |          10 |____ -2 
           \             /     
            -------------      
-----------------------
tensor Name : B
tensor Rank : 3
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -3 ____| 10        2 |____ 1  
           |             |     
           |          10 |____ -4 
           \             /     
            -------------      
Tensor name: la
is_diag    : True
tensor([0.6100, 0.0241, 0.1791, 0.4478, 0.6926, 0.3418, 0.9236, 0.4386, 0.2154,
        0.1430], dtype=torch.float64)

-----------------------
tensor Name : la
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
 

## Imaginary time evolution

In [36]:
Elast = 0.0
for i in range(100):
    A.SetLabels([-1,0,-2])
    B.SetLabels([-3,1,-4])
    la.SetLabels([-2,-3])
    lb.SetLabels([-4,-5])

    ## X =
    #           (0)  (1)
    #            |    |     
    #  (-4) --lb-A-la-B-lb-- (-5) 
    #    
    X = Tor10.Contract(Tor10.Contract(A,la),Tor10.Contract(B,lb))
    lb.SetLabel(-1,idx=1)
    X = Tor10.Contract(lb,X)  
    X.SetName('X')
#     X.Print_diagram()
    
    # <MPS|MPS>
    XNorm = Tor10.Contract(X, X)

    # <MPS|Ham_12|MPS>    
    XH = Tor10.Contract(X, Ham_12)
    XH.SetName('XH')
#     XH.Print_diagram()
    XH.SetLabels([-4,-5,0,1])
#     XH.Print_diagram()
    XHX = Tor10.Contract(X, XH)

    # <MPS|Id1_Sz2|MPS>    
    Z2H = Tor10.Contract(X, Id1_Sz2)
    Z2H.SetName('Z2H')
#     Z2H.Print_diagram()
    Z2H.SetLabels([-4,-5,0,1])
#     Z2H.Print_diagram()
    XZ2X = Tor10.Contract(X, Z2H)
#     print(XZ2X)

    # <MPS|Id1_Sx2|MPS>    
    X2H = Tor10.Contract(X, Id1_Sx2)
    X2H.SetName('Z2H')
#     X2H.Print_diagram()
    X2H.SetLabels([-4,-5,0,1])
#     X2H.Print_diagram()
    XX2X = Tor10.Contract(X, X2H)
#     print(XX2X)



    
    # measurements
#     print(XHX)
#     print(XNorm)
    E = XHX.item()/XNorm.item()
    Elast = E
    print("Energy={:.6f}, <Z2>={:.6f} <X2>={:.6f}".format(E, XZ2X.item(), XX2X.item()))
    
    
    
    
    # imaginary time evolution
    XeH = Tor10.Contract(X,expH_12)
    XeH.SetName('XeH')
#     XeH.Print_diagram()
    XeH.Permute([-4,2,3,-5],by_label=True)
#     XeH.Print_diagram()
    XeH.Contiguous() # necessary?
    XeH = XeH.Reshape([D*2,D*2],N_rowrank=1)
#     XeH.Print_diagram()
    
    A,la,B = Tor10.Svd_truncate(XeH,D)
    la *= la.Norm()**-1 # re-normalize the norm of la
#     A.Print_diagram()
    A = A.Reshape([D,2,D], new_labels=[-1,0,-2], N_rowrank=1)
    B = B.Reshape([D,2,D], new_labels=[-3,1,-4], N_rowrank=1)
#     A.Print_diagram()
#     B.Print_diagram()
    # de-contract the lb tensor , so it returns to 
    #             
    #            |     |     
    #       --lb-A'-la-B'-lb-- 
    #
    # again, but A' and B' are updated 

    lb_inv = Tor10.Inverse(lb)
#     lb_inv.Print_diagram()
    A = Tor10.Contract(lb_inv, A)
    B = Tor10.Contract(B, lb_inv)

    # translation symmetry, exchange A and B site
    A,B = B,A
    la,lb = lb,la     

Energy=3.794316, <Z2>=-0.637150 <X2>=28.055247
Energy=3.705335, <Z2>=0.228403 <X2>=2.250374
Energy=2.239070, <Z2>=-0.073066 <X2>=0.769575
Energy=-0.079898, <Z2>=0.085022 <X2>=0.059124
Energy=-2.786138, <Z2>=0.119098 <X2>=-0.530738
Energy=-3.304147, <Z2>=0.081852 <X2>=-0.795264
Energy=-3.944411, <Z2>=0.138930 <X2>=-0.930203
Energy=-3.896821, <Z2>=0.049368 <X2>=-0.954973
Energy=-4.012232, <Z2>=0.081400 <X2>=-0.973378
Energy=-3.989126, <Z2>=0.028129 <X2>=-0.976540
Energy=-4.010100, <Z2>=0.042170 <X2>=-0.980257
Energy=-4.004264, <Z2>=0.016613 <X2>=-0.981582
Energy=-4.008264, <Z2>=0.021339 <X2>=-0.982741
Energy=-4.006969, <Z2>=0.009831 <X2>=-0.983290
Energy=-4.007759, <Z2>=0.010872 <X2>=-0.983675
Energy=-4.007488, <Z2>=0.005731 <X2>=-0.983873
Energy=-4.007648, <Z2>=0.005623 <X2>=-0.983997
Energy=-4.007594, <Z2>=0.003287 <X2>=-0.984062
Energy=-4.007628, <Z2>=0.002953 <X2>=-0.984101
Energy=-4.007617, <Z2>=0.001859 <X2>=-0.984122
Energy=-4.007624, <Z2>=0.001570 <X2>=-0.984134
Energy=-4.007622,