# Sinvular Value Decomposition (SVD)-0

In this tutorial, we show how to perform
* SVD for a rank-2 tensor.
* SVD + truncation for a rank-2 tensor.

## Import relevant modules

In [1]:
import Tor10
import copy

def Tprint(T):
    print(T.Print_diagram())
    print(T)

## SVD for a rank-2 tensor.

In [2]:
M = Tor10.UniTensor([Tor10.Bond(3), Tor10.Bond(3)], N_rowrank=1, name='M', labels=[10, 11])
M.Rand()
Tprint(M)

# three identical ways to perform SVD
U, S, Vt = M.Svd()
U, S, Vt = Tor10.Svd(M)
U, S, Vt = Tor10.linalg.Svd(M)

-----------------------
tensor Name : M
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: M
is_diag    : False
tensor([[0.1485, 0.3770, 0.8812],
        [0.3532, 0.4638, 0.2232],
        [0.6451, 0.9959, 0.1542]], dtype=torch.float64)



In [3]:
# Check M = U S Vt

print(M - Tor10.Contract(Tor10.Contract(U, S), Vt))

Tensor name: 
is_diag    : False
tensor([[-2.2204e-16, -5.5511e-16,  2.2204e-16],
        [-1.1102e-16, -2.2204e-16, -3.0531e-16],
        [-1.1102e-16, -2.2204e-16, -2.7756e-16]], dtype=torch.float64)



In [4]:
# Check Ut U = Id
U.SetName('U')
Tprint(U)

Ut = U.Whole_transpose()
Ut.SetName('Ut')
Tprint(Ut)
Ut.SetLabels([-1, 11])
Ut.Print_diagram()

Ut_U = Tor10.Contract(Ut, U)
Ut_U.SetName('Ut_U')
Tprint(Ut_U)

-----------------------
tensor Name : U
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         3 |____ -1 
           \             /     
            -------------      
None
Tensor name: U
is_diag    : False
tensor([[-0.4976,  0.8535,  0.1550],
        [-0.4156, -0.0778, -0.9062],
        [-0.7614, -0.5153,  0.3934]], dtype=torch.float64)

-----------------------
tensor Name : Ut
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -1 ____| 3         3 |____ 10 
           \             /     
            -------------      
None
Tensor name: Ut
is_diag    : False
tensor([[-0.4976, -0.4156, -0.7614],
        [ 0.8535, -0.0778, -0.5153],
        [ 0.1550, -0.9062,  0.3934]], dtype=torch.float64)

-----------------------
tensor Name : Ut
tensor Rank : 2
has_symmetry: False
on device    

In [5]:
# Check S
S.SetName('S')
Tprint(S)

-----------------------
tensor Name : S
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 3         3 |____ -2 
           \             /     
            -------------      
None
Tensor name: S
is_diag    : True
tensor([1.4912, 0.7318, 0.0528], dtype=torch.float64)



In [6]:
# Check Vt V = Id
Vt.SetName('Vt')
Tprint(Vt)

V = Vt.Whole_transpose()
V.SetName('V')
Tprint(V)
V.SetLabels([10, -2])
V.Print_diagram()

Vt_V = Tor10.Contract(Vt, V)
Vt_V.SetName('Vt_V')
Tprint(Vt_V)

-----------------------
tensor Name : Vt
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -2 ____| 3         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: Vt
is_diag    : False
tensor([[-0.4774, -0.7635, -0.4350],
        [-0.3186, -0.3109,  0.8954],
        [-0.8189,  0.5660, -0.0948]], dtype=torch.float64)

-----------------------
tensor Name : V
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    11 ____| 3         3 |____ -2 
           \             /     
            -------------      
None
Tensor name: V
is_diag    : False
tensor([[-0.4774, -0.3186, -0.8189],
        [-0.7635, -0.3109,  0.5660],
        [-0.4350,  0.8954, -0.0948]], dtype=torch.float64)

-----------------------
tensor Name : V
tensor Rank : 2
has_symmetry: False
on device     

## SVD + truncation for a rank-2 tensor.

In [7]:
M = Tor10.UniTensor([Tor10.Bond(3), Tor10.Bond(3)], N_rowrank=1, name='M', labels=[10, 11])
M.Rand()
Tprint(M)

# three identical ways to perform SVD + truncate
# Uc, Sc, Vtc = M.Svd_truncate() # does not work :(
Uc, Sc, Vtc = Tor10.Svd_truncate(M, 2)
Uc, Sc, Vtc = Tor10.linalg.Svd_truncate(M, 2)

-----------------------
tensor Name : M
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: M
is_diag    : False
tensor([[0.2533, 0.0196, 0.1436],
        [0.7735, 0.5777, 0.5985],
        [0.9166, 0.1952, 0.3900]], dtype=torch.float64)



In [8]:
# Check M ≠ Uc Sc Vtc

print(M - Tor10.Contract(Tor10.Contract(Uc, Sc), Vtc))

Tensor name: 
is_diag    : False
tensor([[-0.0111, -0.0218,  0.0355],
        [-0.0003, -0.0007,  0.0011],
        [ 0.0035,  0.0069, -0.0112]], dtype=torch.float64)



In [9]:
# Check Utc Uc ≠ Id
Uc.SetName('Uc')
Tprint(Uc)

Utc = Uc.Whole_transpose()
Utc.SetName('Utc')
Tprint(Utc)
Utc.SetLabels([-1, 11])
Utc.Print_diagram()

Utc_Uc = Tor10.Contract(Utc, Uc)
Utc_Uc.SetName('Utc_Uc')
Tprint(Utc_Uc)

-----------------------
tensor Name : Uc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         2 |____ -1 
           \             /     
            -------------      
None
Tensor name: Uc
is_diag    : False
tensor([[-0.1833,  0.2407],
        [-0.7350, -0.6774],
        [-0.6528,  0.6951]], dtype=torch.float64)

-----------------------
tensor Name : Utc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -1 ____| 2         3 |____ 10 
           \             /     
            -------------      
None
Tensor name: Utc
is_diag    : False
tensor([[-0.1833, -0.7350, -0.6528],
        [ 0.2407, -0.6774,  0.6951]], dtype=torch.float64)

-----------------------
tensor Name : Utc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------     

In [10]:
# Check Sc
Sc.SetName('Sc')
Tprint(Sc)

-----------------------
tensor Name : Sc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 2         2 |____ -2 
           \             /     
            -------------      
None
Tensor name: Sc
is_diag    : True
tensor([1.5167, 0.3213], dtype=torch.float64)



In [11]:
# Check Vtc Vc ≠ Id
Vtc.SetName('Vtc')
Tprint(Vtc)

Vc = Vtc.Whole_transpose()
Vc.SetName('Vc')
Tprint(Vc)
Vc.SetLabels([10, -2])
Vc.Print_diagram()

Vtc_Vc = Tor10.Contract(Vtc, Vc)
Vtc_Vc.SetName('Vtc_Vc')
Tprint(Vtc_Vc)

-----------------------
tensor Name : Vtc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -2 ____| 2         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: Vtc
is_diag    : False
tensor([[-0.8000, -0.3664, -0.4752],
        [ 0.5420, -0.7809, -0.3104]], dtype=torch.float64)

-----------------------
tensor Name : Vc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    11 ____| 3         2 |____ -2 
           \             /     
            -------------      
None
Tensor name: Vc
is_diag    : False
tensor([[-0.8000,  0.5420],
        [-0.3664, -0.7809],
        [-0.4752, -0.3104]], dtype=torch.float64)

-----------------------
tensor Name : Vc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      