# Sinvular Value Decomposition (SVD)-0

In this tutorial, we show how to perform
* SVD for a rank-2 tensor.
* SVD + truncation for a rank-2 tensor.

## API change
* `N_rowrank-->rowrank`.

## Import relevant modules

In [1]:
import Tor10
import copy

def Tprint(T):
    print(T.Print_diagram())
    print(T)

## SVD for a rank-2 tensor.

In [2]:
M = Tor10.UniTensor([Tor10.Bond(3), Tor10.Bond(3)], rowrank=1, name='M', labels=[10, 11])
M.Rand()
Tprint(M)

# three identical ways to perform SVD
U, S, Vt = M.Svd()
U, S, Vt = Tor10.Svd(M)
U, S, Vt = Tor10.linalg.Svd(M)

-----------------------
tensor Name : M
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: M
is_diag    : False
tensor([[0.4751, 0.0908, 0.5339],
        [0.7093, 0.8224, 0.5454],
        [0.8366, 0.7248, 0.8520]], dtype=torch.float64)



In [3]:
# Check M = U S Vt

print(M - Tor10.Contract(Tor10.Contract(U, S), Vt))

Tensor name: 
is_diag    : False
tensor([[ 1.6653e-16,  3.7470e-16,  4.4409e-16],
        [ 1.1102e-16, -1.1102e-16,  2.2204e-16],
        [-1.1102e-16, -2.2204e-16, -1.1102e-16]], dtype=torch.float64)



In [4]:
# Check Ut U = Id
U.SetName('U')
Tprint(U)

Ut = U.Whole_transpose()
Ut.SetName('Ut')
Tprint(Ut)
Ut.SetLabels([-1, 11])
Ut.Print_diagram()

Ut_U = Tor10.Contract(Ut, U)
Ut_U.SetName('Ut_U')
Tprint(Ut_U)

-----------------------
tensor Name : U
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         3 |____ -1 
           \             /     
            -------------      
None
Tensor name: U
is_diag    : False
tensor([[-0.3327,  0.8055, -0.4905],
        [-0.6130, -0.5799, -0.5366],
        [-0.7166,  0.1222,  0.6867]], dtype=torch.float64)

-----------------------
tensor Name : Ut
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -1 ____| 3         3 |____ 10 
           \             /     
            -------------      
None
Tensor name: Ut
is_diag    : False
tensor([[-0.3327, -0.6130, -0.7166],
        [ 0.8055, -0.5799,  0.1222],
        [-0.4905, -0.5366,  0.6867]], dtype=torch.float64)

-----------------------
tensor Name : Ut
tensor Rank : 2
has_symmetry: False
on device    

In [5]:
# Check S
S.SetName('S')
Tprint(S)

-----------------------
tensor Name : S
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 3         3 |____ -2 
           \             /     
            -------------      
None
Tensor name: S
is_diag    : True
tensor([1.9474, 0.3902, 0.0511], dtype=torch.float64)



In [6]:
# Check Vt V = Id
Vt.SetName('Vt')
Tprint(Vt)

V = Vt.Whole_transpose()
V.SetName('V')
Tprint(V)
V.SetLabels([10, -2])
V.Print_diagram()

Vt_V = Tor10.Contract(Vt, V)
Vt_V.SetName('Vt_V')
Tprint(Vt_V)

-----------------------
tensor Name : Vt
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -2 ____| 3         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: Vt
is_diag    : False
tensor([[-0.6123, -0.5411, -0.5764],
        [ 0.1885, -0.8080,  0.5582],
        [-0.7678,  0.2331,  0.5968]], dtype=torch.float64)

-----------------------
tensor Name : V
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    11 ____| 3         3 |____ -2 
           \             /     
            -------------      
None
Tensor name: V
is_diag    : False
tensor([[-0.6123,  0.1885, -0.7678],
        [-0.5411, -0.8080,  0.2331],
        [-0.5764,  0.5582,  0.5968]], dtype=torch.float64)

-----------------------
tensor Name : V
tensor Rank : 2
has_symmetry: False
on device     

## SVD + truncation for a rank-2 tensor.

In [7]:
M = Tor10.UniTensor([Tor10.Bond(3), Tor10.Bond(3)], rowrank=1, name='M', labels=[10, 11])
M.Rand()
Tprint(M)

# three identical ways to perform SVD + truncate
# Uc, Sc, Vtc = M.Svd_truncate() # does not work :(
Uc, Sc, Vtc = Tor10.Svd_truncate(M, 2)
Uc, Sc, Vtc = Tor10.linalg.Svd_truncate(M, 2)

-----------------------
tensor Name : M
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: M
is_diag    : False
tensor([[0.0250, 0.4958, 0.5691],
        [0.9460, 0.5817, 0.2471],
        [0.5930, 0.0340, 0.7192]], dtype=torch.float64)



In [8]:
# Check M ≠ Uc Sc Vtc

print(M - Tor10.Contract(Tor10.Contract(Uc, Sc), Vtc))

Tensor name: 
is_diag    : False
tensor([[-0.1017,  0.2639, -0.0750],
        [-0.0460,  0.1194, -0.0339],
        [ 0.1251, -0.3246,  0.0923]], dtype=torch.float64)



In [9]:
# Check Utc Uc ≠ Id
Uc.SetName('Uc')
Tprint(Uc)

Utc = Uc.Whole_transpose()
Utc.SetName('Utc')
Tprint(Utc)
Utc.SetLabels([-1, 11])
Utc.Print_diagram()

Utc_Uc = Tor10.Contract(Utc, Uc)
Utc_Uc.SetName('Utc_Uc')
Tprint(Utc_Uc)

-----------------------
tensor Name : Uc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 3         2 |____ -1 
           \             /     
            -------------      
None
Tensor name: Uc
is_diag    : False
tensor([[-0.3751,  0.7010],
        [-0.7288, -0.6274],
        [-0.5729,  0.3392]], dtype=torch.float64)

-----------------------
tensor Name : Utc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -1 ____| 2         3 |____ 10 
           \             /     
            -------------      
None
Tensor name: Utc
is_diag    : False
tensor([[-0.3751, -0.7288, -0.5729],
        [ 0.7010, -0.6274,  0.3392]], dtype=torch.float64)

-----------------------
tensor Name : Utc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------     

In [10]:
# Check Sc
Sc.SetName('Sc')
Tprint(Sc)

-----------------------
tensor Name : Sc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 2         2 |____ -2 
           \             /     
            -------------      
None
Tensor name: Sc
is_diag    : True
tensor([1.4573, 0.6152], dtype=torch.float64)



In [11]:
# Check Vtc Vc ≠ Id
Vtc.SetName('Vtc')
Tprint(Vtc)

Vc = Vtc.Whole_transpose()
Vc.SetName('Vc')
Tprint(Vc)
Vc.SetLabels([10, -2])
Vc.Print_diagram()

Vtc_Vc = Tor10.Contract(Vtc, Vc)
Vtc_Vc.SetName('Vtc_Vc')
Tprint(Vtc_Vc)

-----------------------
tensor Name : Vtc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -2 ____| 2         3 |____ 11 
           \             /     
            -------------      
None
Tensor name: Vtc
is_diag    : False
tensor([[-0.7127, -0.4319, -0.5528],
        [-0.6093, -0.0095,  0.7929]], dtype=torch.float64)

-----------------------
tensor Name : Vc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    11 ____| 3         2 |____ -2 
           \             /     
            -------------      
None
Tensor name: Vc
is_diag    : False
tensor([[-0.7127, -0.6093],
        [-0.4319, -0.0095],
        [-0.5528,  0.7929]], dtype=torch.float64)

-----------------------
tensor Name : Vc
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      