# Sinvular Value Decomposition (SVD)-2

In this tutorial, we show how to write a function that perform rank-n SVD/SVD truncate.

## API change
* Require Tor10 v 0.3.7 or higher.
* `N_rowrank-->rowrank`.

In [1]:
import Tor10
import copy
import numpy as np

def Tprint(T):
    print(T.Print_diagram())
    print(T)

In [2]:
def SVD_n(T):
    M = T.GetBlock()
    UM, S, VtM = M.Svd()
#     T.Print_diagram()
#     UM.Print_diagram()
#     VtM.Print_diagram()
    
    rowrank = T.rowrank
    rank = len(T.labels)
    colrank = rank - rowrank
    
    U_labels = np.concatenate([T.labels[:rowrank],UM.labels[-1:]])
    Vt_labels = np.concatenate([VtM.labels[:1], T.labels[-colrank:]])
    
    U_bonds = np.concatenate([T.bonds[:rowrank],UM.bonds[-1:]])
    Vt_bonds = np.concatenate([VtM.bonds[:1], T.bonds[-colrank:]])

    U = Tor10.UniTensor(bonds=U_bonds, labels=U_labels, rowrank=T.rowrank, name='U') 
    U.PutBlock(UM)
    
    Vt = Tor10.UniTensor(bonds=Vt_bonds, labels=Vt_labels, rowrank=1, name='Vt')
    Vt.PutBlock(VtM)
                          
    return U, S, Vt

In [3]:
bd = Tor10.Bond(2)
T = Tor10.UniTensor([bd, bd, bd], rowrank=1, name='T')
T.Rand()
U, S, Vt = SVD_n(T)
Tprint(U)
Tprint(S)
Tprint(Vt)

-----------------------
tensor Name : U
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         2 |____ -1 
           \             /     
            -------------      
None
Tensor name: U
is_diag    : False
tensor([[-0.4686, -0.8834],
        [-0.8834,  0.4686]], dtype=torch.float64)

-----------------------
tensor Name : 
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 2         2 |____ -2 
           \             /     
            -------------      
None
Tensor name: 
is_diag    : True
tensor([0.9258, 0.3071], dtype=torch.float64)

-----------------------
tensor Name : Vt
tensor Rank : 3
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    -2 ____| 2         2 |____ 1  
           |        

In [4]:
bd = Tor10.Bond(2)
T = Tor10.UniTensor([bd, bd, bd, bd], rowrank=2, name='T')
T.Rand()
U, S, Vt = SVD_n(T)
Tprint(U)
Tprint(S)
Tprint(Vt)

-----------------------
tensor Name : U
tensor Rank : 3
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         4 |____ -1 
           |             |     
     1 ____| 2           |        
           \             /     
            -------------      
None
Tensor name: U
is_diag    : False
tensor([[[-0.4818,  0.0644, -0.5358, -0.6904],
         [-0.5051, -0.3843,  0.7310, -0.2507]],

        [[-0.5886, -0.3210, -0.3514,  0.6535],
         [-0.4078,  0.8632,  0.2347,  0.1830]]], dtype=torch.float64)

-----------------------
tensor Name : 
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 4         4 |____ -2 
           \             /     
            -------------      
None
Tensor name: 
is_diag    : True
tensor([2.6068, 0.8620, 0.3056, 0.2705], dtype=torch.float64)

--------------------

In [5]:
def SVD_truncate_n(T, Dcut):
    M = T.GetBlock()
    UM, S, VtM = M.Svd_truncate(Dcut)
#     T.Print_diagram()
#     UM.Print_diagram()
#     VtM.Print_diagram()
    
    rowrank = T.rowrank
    rank = len(T.labels)
    colrank = rank - rowrank
    
    U_labels = np.concatenate([T.labels[:rowrank],UM.labels[-1:]])
    Vt_labels = np.concatenate([VtM.labels[:1], T.labels[-colrank:]])
    
    U_bonds = np.concatenate([T.bonds[:rowrank],UM.bonds[-1:]])
    Vt_bonds = np.concatenate([VtM.bonds[:1], T.bonds[-colrank:]])

    U = Tor10.UniTensor(bonds=U_bonds, labels=U_labels, rowrank=T.rowrank, name='U') 
    U.PutBlock(UM)
    
    Vt = Tor10.UniTensor(bonds=Vt_bonds, labels=Vt_labels, rowrank=1, name='Vt')
    Vt.PutBlock(VtM)
                          
    return U, S, Vt

In [6]:
bd = Tor10.Bond(2)
T = Tor10.UniTensor([bd, bd, bd, bd], rowrank=2, name='T')
T.Rand()
U, S, Vt = SVD_truncate_n(T,4)
Tprint(U)
Tprint(S)
Tprint(Vt)
U, S, Vt = SVD_truncate_n(T,2)
Tprint(U)
Tprint(S)
Tprint(Vt)

-----------------------
tensor Name : U
tensor Rank : 3
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
     0 ____| 2         4 |____ -1 
           |             |     
     1 ____| 2           |        
           \             /     
            -------------      
None
Tensor name: U
is_diag    : False
tensor([[[-0.7174, -0.2258,  0.3764, -0.5411],
         [-0.3002, -0.3616,  0.3658,  0.8033]],

        [[-0.5723,  0.0621, -0.7982,  0.1775],
         [-0.2604,  0.9024,  0.2957,  0.1743]]], dtype=torch.float64)

-----------------------
tensor Name : 
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : True
            -------------      
           /             \     
    -1 ____| 4         4 |____ -2 
           \             /     
            -------------      
None
Tensor name: 
is_diag    : True
tensor([2.2051, 0.4381, 0.3453, 0.0397], dtype=torch.float64)

--------------------