# Tor10 v3.0

In [2]:
import Tor10 
import numpy as np 
import torch 
import copy

## Bond
* Bond = local vector space.
* `Tor10.Bond(D)` creates a D-dimensional local vector space.
  * D≥1 is an integer.
  * Implicitly, it corresponds to a basis $\vec{e}_1, \vec{e}_2, \dots, \vec{e}_D$

In [3]:
bd1 = Tor10.Bond(1)
bd2 = Tor10.Bond(2)
bd3 = Tor10.Bond(3)
bd4 = Tor10.Bond(4)
for b in [bd1, bd2, bd3, bd4]:
    print(b)

Dim = 1 |
REG     :

Dim = 2 |
REG     :

Dim = 3 |
REG     :

Dim = 4 |
REG     :



## Tensor

### Rank-0 tensor

In [4]:
# create a rank-0 tensor
a = Tor10.UniTensor(bonds=[], name='a')
a = Tor10.UniTensor(bonds=[], N_rowrank=0, name='a')
a.Print_diagram()
print(a)

# set value
a.SetElem([10])
print(a)
print(a-10)

# get value
print(a.item())

-----------------------
tensor Name : a
tensor Rank : 0
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           \             /     
            -------------      
Tensor name: a
is_diag    : False
tensor([0.], dtype=torch.float64)

Tensor name: a
is_diag    : False
tensor([10.], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([0.], dtype=torch.float64)

10.0


In [5]:

a.Print_diagram()
print(a)

-----------------------
tensor Name : a
tensor Rank : 0
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           \             /     
            -------------      
Tensor name: a
is_diag    : False
tensor([10.], dtype=torch.float64)



### Rank-1 tensor
Consider a rank-1 tensor (=vector) $T_i$ where $i=1, 2, \dots, D$. We want to distinguish a row vector and a column vector. 

In [8]:
a = Tor10.UniTensor(bonds=[Tor10.Bond(2)], N_rowrank=0, labels=[9], name='a')
a.Print_diagram()
print(a)

b = Tor10.UniTensor(bonds=[Tor10.Bond(2)], N_rowrank=1, labels=[10], name='b')
b.Print_diagram()
print(b)

-----------------------
tensor Name : a
tensor Rank : 1
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
           |           2 |____ 9  
           \             /     
            -------------      
Tensor name: a
is_diag    : False
tensor([0., 0.], dtype=torch.float64)

-----------------------
tensor Name : b
tensor Rank : 1
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 2           |        
           \             /     
            -------------      
Tensor name: b
is_diag    : False
tensor([0., 0.], dtype=torch.float64)



In [9]:
c = Tor10.Contract(a,b)
c.Print_diagram()
print(c)

-----------------------
tensor Name : 
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
            -------------      
           /             \     
    10 ____| 2         2 |____ 9  
           \             /     
            -------------      
Tensor name: 
is_diag    : False
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)



In [41]:
a = Tor10.UniTensor(bonds=[Tor10.Bond(3,Tor10.BD_BRA),Tor10.Bond(4,Tor10.BD_BRA)])
a.Print_diagram()
print(a.is_braket)
print(a)

-----------------------
tensor Name : 
tensor Rank : 2
has_symmetry: False
on device     : cpu
is_diag       : False
braket_form : True
       <bra|             |ket> 
           ---------------     
           |             |     
     0 < __| 3           |        
           |             |     
     1 < __| 4           |        
           |             |     
           ---------------     
True
Tensor name: 
braket_form : True
is_diag    : False
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)



In [3]:
## Example for Tor10 v0.3
## Kai-Hsin Wu

In [6]:
## Bond:
#=======================================
## Non-symmetry:
bd_x = Tor10.Bond(3,Tor10.BD_KET) ## This is equivalent to Tor10.Bond(3,Tor10.BD_REGULAR)
# bd_x = Tor10.Bond(3) ## This is equivalent to Tor10.Bond(3,Tor10.BD_REGULAR)
bd_y = Tor10.Bond(4,Tor10.BD_BRA)
bd_z = Tor10.Bond(3,Tor10.BD_KET)
print(bd_x)
print(bd_y)
print(bd_z)
print(bd_x==bd_z) ## This should be true
print(bd_x is bd_z) ## This should be false
print(bd_x==bd_y) ## This should be false

Dim = 3 |
KET     :

Dim = 4 |
BRA     :

Dim = 3 |
KET     :

True
False
False


In [10]:
x = 'a'
y = 'a'
print(x is y)
print(x == y)

True
True
